### ISSUE TITLE
monaco-vue run error

### ISSUE THREAD

**Issue by ygj6** [rebornix/monaco-vue#2]
How can I solve this problem?

D:\Zcq\monaco-vue\monaco-vue-master>yarn install
yarn install v1.2.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/gulp-tsb/-/gulp-tsb-2.0.4.tgz: connect ETIMEDOUT 104.16.60.173:443".
info If you think this is a bug, please open a bug report with the information provided in "D:\Zcq\monaco-vue\monaco-vue-master\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

D:\Zcq\monaco-vue\monaco-vue-master>

**Comment by harkue** [comment]
del yarn.lock  and rerun "yarn install"
